### ISSUE TITLE
[Request] Ability to remotely kill a session

### ISSUE THREAD

**Issue by HelgeSverre** [inconshreveable/ngrok#421]
There are circumstances wherre I am working from home or at work and have to leave ngrok open so that clients can look at work in progress, but then when i have relocated (work) i am unable to use the same reserved subdomains because ngrok is already running at home using them.

It would be great to be able to login to the ngrok dashboard (via the website) and kill active sessions to free up a subdomain or session in cases like this.

**Comment by HelgeSverre** [comment]
Nevermind, i just read that this repo is for ngrok 1 only, this is a ngrok 2 feature request.

**Comment by Michael-Qin-Bose** [comment]
So.... where do the ngrok2 feature requests go? Because I'm sure lots of people have this problem. Doesn't seem like ngrok2 has a repo

**Comment by rdavila** [comment]
@inconshreveable I'll appreciate to have this feature in Ngrok, sometimes my coworker or myself forget to shutdown Ngrok and this prevent us from receiving external API calls that come through callbacks from external services. This problem is more notorious when we work with people in different time zones, we don't have other option than wait for our colleague to shutdown Ngrok.

**Comment by knagode** [comment]
Just add an endpoint which executes `killall ngrok`. I added wrapper for ngrok which always try to kill existing connection .. Few lines of code and all problems disappeared ..

**Comment by michaeldaw** [comment]
Still... it'd be nice to have this built in.

**Comment by ryanckulp** [comment]
hey gang, remote founder here. we just ripped this in case it's useful for others:
https://blog.fomo.com/remotely-kill-ngrok-session/

**Comment by jchatel** [comment]
I guess the first time this happens to you, you are bound to lose time because there are no possibilities to close a session. I tried deleting the reserved domain, re-generate authentication... The remote session still going strong. Sounds to me like a critical feature is missing there. Terribly disappointing.
