### ISSUE TITLE
connection reset by peer

### ISSUE THREAD

**Issue by liuadmin** [inconshreveable/ngrok#480]
Failed to read message: read tcp 172.16.253.243:4443->183.129.165.161:63311: read: connection reset by peer

**Comment by Ezreal147** [comment]
I have the same problem

**Comment by letitfly** [comment]
I have the same! Any solution anyone?

**Comment by liaolunhui** [comment]
+1

**Comment by dprothero** [comment]
I've seen this in the wild. Are y'all behind a corporate firewall, by any chance? Not sure if that's it, but it's a theory.

**Comment by jsRuner** [comment]
me too

**Comment by rafaelbpa** [comment]
Same here. How you guys fixed it?

**Comment by akkijadhav123** [comment]
Any update on the same ?

**Comment by 3tbraden** [comment]
I was behind a corporate firewall and writing Go code with the http package and running into this problem. It seemed to be a problem with the Go http package and I switched to [resty](https://github.com/go-resty/resty) and the problem gone.

**Comment by msuno** [comment]
I have the same.

**Comment by yuquant** [comment]
顶

**Comment by wuyungang3** [comment]
how to fix it,anybody can help me ?

**Comment by martynchamberlin** [comment]
For what it's worth, I was having this issue too and I figured it out. Probably because of some kind of firewall device-obscurity rule that's setup in my local network, when both the Ngrok device _and_ another device are connected by Ethernet, this breaks it for _all_ devices that try to connect, regardless of whether they're in the same network or not. 

In other words, I have Ngrok set up on a Linux machine. It's hard-wired in via Ethernet. Then I have a Mac that tries to connect to the Linux via Ngrok. It doesn't work if the Mac is on the same Ethernet network. If I unplug the Mac and go to WiFi, then it works. If the Mac is plugged in, then any _other_ devices that try to connect likewise will fail. Once I unplug the Mac from Ethernet, it works on those external devices as well. 

I'm pretty weak on my networking skills and this blows my mind. Just posting this here in case it helps any of you.

**Comment by karoenven** [comment]
> 

hi，@liuadmin，did you fixed it ??, i had same err in my server.

**Comment by liuadmin** [comment]
@karoenven  no,I used other software to replace it, it's  nps , url is : https://github.com/ehang-io/nps

**Comment by liuadmin** [comment]
We can replace it with other software,  https://github.com/ehang-io/nps
