### ISSUE TITLE
Create a DNS CNAME record

### ISSUE THREAD

**Issue by DocKali** [inconshreveable/ngrok#605]
Hi,

I'm currently trying to use custom hostname with Ngrok. I reserve a subdomain, no problem about that. But there's a step I can't figure out. It's about creating a DNS CNAME record and linked it to my hostname in Ngrok. How can I do that?

**Comment by bdanklin** [comment]
https://ngrok.com/docs#http-custom-domains Its linked here but I cant see that button

**Comment by Leggerla** [comment]
Same question.

**Comment by mitchazj** [comment]
Also stuck on this

**Comment by mitchazj** [comment]
Fixed it for anyone else who also runs into this issue: the docs are out of date.

You need to create a new reserved domain and *actually use the third-party domain when reserving* (instead of creating a new subdomain under ngrok.io). You will then be able to view immediately (in the drawer that slides out from the right) the CNAME record to use.

You'll also need to update your config file so you're pointing directly to your third-party domain

**Comment by caseysoftware** [comment]
These forums are unmonitored. For active support, check out our slack community: https://ngrok.com/slack
