### ISSUE TITLE
Ngrok is contain under "proxy Avoidance" category

### ISSUE THREAD

**Issue by mDineshRaja** [inconshreveable/ngrok#619]
We have face the below issue:

The Bluecoat category is:   Proxy Avoidance. Sites in this category may pose a security risk to network   resources and company information, and are blocked by your organization.

Why ngrok site suddenly move to proxy avoidance category, let us know to me for the reason, since we will development work dependent in this tool.

**Comment by Libross** [comment]
Hi, probably old topic, but just for info to the others having same issue...
Bluecoat is proxy software with capability to filter outgoing traffic based on predefined rules (or some automated considerations if the web address is safe or not).

In example in our company our IT department is also using bluecoat and it is blocking access to web like rapidshare or hellshare to prevent security risks/downloading anything from risky sources, but sometimes even legit web sites are blocked.

If you received the message similar to the one showed in original post, it is not related with ngrok service itself... it just mean that your local company IT department set up the rules the way that ngrok servers falls to the suspicious category (as mentioned sometimes even trustworthy web sites are blocked accidentally). 

If you need ngrok for development in your company, but you get blocked by proxy, just contact your IT department to modify the rules (like adding ngrok to white list), so that the communication is not blocked.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
