### ISSUE TITLE
ngrok doesn't pass Set-Cookie header sent by server

### ISSUE THREAD

**Issue by shailysangwan** [inconshreveable/ngrok#622]
I'm trying to use session authentication for my django application. When I connect the frontend app to the locally running backend server using the localhost address, the browser sets the cookies sent in the Set-Cookie header ( includes session_id and csrf_token ) and the user is able to authenticate himself. However, when I use an ngrok URL that points to the same server, the browser doesn't set the session_id and csrf_token cookies and the user is Forbidden ( 403 http response ) from accessing the protected endpoints.

**Comment by Danon** [comment]
Hello, I had the same issue. 

In my case, I thought `ngrok` didn't pass the cookies, but it turns out my `localhost` were also **missing** cookies! I just didn't notice it, because my browser **cached** the cookies and allowed me to use the csrf.

To verify that, you can open your `localhost` application in **incognito** mode, and you will see the header is missing there too!

To fix it, use `ensure_csrf_cookie` decorator:

```py
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie

@ensure_csrf_cookie
def index(request):
    return render(request, 'index.html')
```

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
