### ISSUE TITLE
ngrok localhost hosting problem

### ISSUE THREAD

**Issue by azamet90** [inconshreveable/ngrok#628]
im starting ngrok with ngrok http 3000
after i start apache2
first im checking https://localhost/
i see a different page
after i open my ngrok page and i see different page...
so the page im seeing on ngrok isnt the page i have in /var/www/html/ and www folder does not have index file!

im using kali linux but which folder is hosted with ngrok after starting it?

[Location .ngrok2/ngrok.yml ]
tunnels:
first-app:
addr: 80
proto: http
second-app:
addr: 3000
proto: http

and i tryed this one then this is giving error ...

**Comment by monitorikdam** [comment]
http://a62f6e29.ngrok.io

**Comment by azamet90** [comment]
> http://a62f6e29.ngrok.io

and?

**Comment by monitorikdam** [comment]
you need apache ??

**Comment by monitorikdam** [comment]
http://39f2127c.ngrok.io
this is port 80

**Comment by azamet90** [comment]
> http://39f2127c.ngrok.io
> this is port 80

yeah but i need port 3000 and host my /var/www/html/ folder same time how to do it?

**Comment by monitorikdam** [comment]
you open it with linux 

/var/www/html/39f2127c.ngrok.io

**Comment by azamet90** [comment]
> you open it with linux
> 
> /var/www/html/39f2127c.ngrok.io

i cannot understand nothing from this post im sorry but what should i understand from this /var/www/html/39f2127c.ngrok.io :/

**Comment by Libross** [comment]
Back to the original problem, I am new user and not much using ngrok http type of connection... just trying to help... 
But as I understand from your first post, you start `ngrok http 3000` this means that your local web server must be running on port 3000 and it is then redirected to generated ngrok web address - there it will be running on default web port 80 - so that you can only use address like xxxx.ngrok.io to access your local web server... 
if your web server is running on port 3000 it makes no sense to try to open address https://localhost/ on your machine and compare with ngrok generated link as https://localhost/is pointing to default port 80 (so different instance of web server probably, not the one running on port 3000, but maybe some default page, depending on what type of web server you are running)...

Maybe I wrongly understand your problem, but the original post is quite confusing...

**Comment by caseysoftware** [comment]
We disabled Kali support due to the large number of malicious users. If you have a legitimate use case, please contact Support. We do not allow "ethical hacking"
