### ISSUE TITLE
Error 802, ngrok down?

### ISSUE THREAD

**Issue by jweled** [inconshreveable/ngrok#797]
No matter what I do, I receive an internal server error.

Here's the log:

`t=2021-10-31T00:16:14+0000 lvl=info msg="no configuration paths supplied"
t=2021-10-31T00:16:14+0000 lvl=info msg="using configuration at default config path" path=/home/runner/.ngrok2/ngrok.yml
t=2021-10-31T00:16:14+0000 lvl=info msg="open config file" path=/home/runner/.ngrok2/ngrok.yml err=nil
t=2021-10-31T00:16:14+0000 lvl=info msg="starting web service" obj=web addr=127.0.0.1:4040
t=2021-10-31T00:16:14+0000 lvl=info msg="tunnel session started" obj=tunnels.session
t=2021-10-31T00:16:14+0000 lvl=info msg="client session established" obj=csess id=95fe7e3e85dc
t=2021-10-31T00:16:14+0000 lvl=eror msg="session closing" obj=tunnels.session err="internal server error\r\n\r\nERR_NGROK_802\r\n"
t=2021-10-31T00:16:14+0000 lvl=info msg="accept failed" obj=csess id=95fe7e3e85dc err="reconnecting session closed"
t=2021-10-31T00:16:14+0000 lvl=info msg="received stop request" obj=app stopReq="{err:0xc000440010 restart:false}"
t=2021-10-31T00:16:14+0000 lvl=eror msg="terminating with error" obj=app err="internal server error\r\n\r\nERR_NGROK_802\r\n"
t=2021-10-31T00:16:14+0000 lvl=crit msg="command failed" err="internal server error\r\n\r\nERR_NGROK_802\r\n"
internal server error

ERR_NGROK_802

`

I think that ngrok might be down right now.

**Comment by Diegolfa** [comment]
Same here

**Comment by korovindenis** [comment]
Same here

**Comment by injarapuveerabrahmendra** [comment]
same here any solution

**Comment by Diegolfa** [comment]
> same here any solution

whot, you literally commented the same time i browse this thread again to see if anyone else commented lol

**Comment by BoostedPenguin** [comment]
It's probably going to get fixed real soon, but in case you need to use it now - you can delete the auth token from your yml file. However, you will lose some of the functionality.

**Comment by edmundo096** [comment]
Had the same issue around the same time or earlier.
Tried with other servers like EU, JP, but no luck.

Now, after maybe 16 hours or more, it seems to be working for me, on the US region.

Weird thing is, the [status page](https://status.ngrok.com/) didn't reported anything, even after 3 hours or more passed since the incident started and reported here, and still haven't, which make me wonder how reliable that status page is, or how well their monitoring tools are setup, or if it's something off their boundaries and more about the clients networks (ISPs?).

It would be good if they had at least some kind of opt-in reporting for this kind of issues on their official clients, so to let others aware when this kind of "isolated cases" occur, which do happen from time to time (#650), specially for their pro subscribers.

**Comment by chimit** [comment]
Looks like ngrok started blocking anonymous connections recently. So to bypass it you should specify your ngrok `authtoken`:
```
ngrok authtoken {ngrok_authtoken}
```
Authtoken can be found in the ngrok [dashboard](https://dashboard.ngrok.com).

**Comment by caseysoftware** [comment]
These issues are unmonitored.

For status updates, visit https://status.ngrok.com/

For community/discussion, visit: http://ngrok.com/slack
