### ISSUE TITLE
Passing a custom hostname while creating the ngrok instance programatically

### ISSUE THREAD

**Issue by subhanahmed047** [inconshreveable/ngrok#808]
I'm trying to create a ngrok instance with a custom hostname, but It looks like the ngrok options object doesn't accept the hostname, so how do we create an instance that is using our custom domain rather than default ngrok.io? 

Here is how I'm doing it:
```
await ngrok.connect({
    authtoken: TOKEN,
    hostname: 'mydomain.io', // this doesn't exist
    subdomain: uuid,
    region: 'au',
    port,
 });
```

**Comment by wangruihuano** [comment]
demo

**Comment by wangruihuano** [comment]
> demo

dd

**Comment by wangruihuano** [comment]
I'm trying to create a ngrok instance with a custom hostname, but It looks like the ngrok options object doesn't accept the hostname, so how do we create an instance that is using our custom domain rather than default ngrok.io?
I'm trying to create a ngrok instance with a custom hostname, but It looks like the ngrok options object doesn't accept the hostname, so how do we create an instance that is using our custom domain rather than default ngrok.io?
I'm trying to create a ngrok instance with a custom hostname, but It looks like the ngrok options object doesn't accept the hostname, so how do we create an instance that is using our custom domain rather than default ngrok.io?

**Comment by wangruihuano** [comment]
> I'm trying to create a ngrok instance with a custom hostname, but It looks like the ngrok options object doesn't accept the hostname, so how do we create an instance that is using our custom domain rather than default ngrok.io? I'm trying to create a ngrok instance with a custom hostname, but It looks like the ngrok options object doesn't accept the hostname, so how do we create an instance that is using our custom domain rather than default ngrok.io? I'm trying to create a ngrok instance with a custom hostname, but It looks like the ngrok options object doesn't accept the hostname, so how do we create an instance that is using our custom domain rather than default ngrok.io?

I'm trying to create a ngrok instance with a custom hostname, but It looks like the ngrok options object doesn't accept the hostname, so how do we create an instance that is using our custom domain rather than default ngrok.io?I'm trying to create a ngrok instance with a custom hostname, but It looks like the ngrok options object doesn't accept the hostname, so how do we create an instance that is using our custom domain rather than default ngrok.io?I'm trying to create a ngrok instance with a custom hostname, but It looks like the ngrok options object doesn't accept the hostname, so how do we create an instance that is using our custom domain rather than default ngrok.io?I'm trying to create a ngrok instance with a custom hostname, but It looks like the ngrok options object doesn't accept the hostname, so how do we create an instance that is using our custom domain rather than default ngrok.io?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
