### ISSUE TITLE
Tunnel XXXXXX not found (ERR_NGROK_3200)

### ISSUE THREAD

**Issue by avva555** [inconshreveable/ngrok#828]
URL is generated but its working in devices are sharing same wifi if i open the URL provided by ngrok its giving error like this

Tunnel [generated url] not found (ERR_NGROK_3200)

please provide some solution for this

**Comment by avva555** [comment]
any one facing this issue?

**Comment by avva555** [comment]
@all please provide some solution

**Comment by LukasUnbesiegt** [comment]
having same issue and it is very frustrating .

**Comment by avva555** [comment]
i changed wifi to jio dongle it started working i dont know what was the issue

**Comment by avva555** [comment]
if any one have better than this approach let me know

**Comment by yytambaya** [comment]
I think this issue is caused by Ngrok firewalls due to suspicious activities.

You have 3 ways of fixing it

Solution #1: Authenticate/Re-authenticate with your token from ngrok
How to do that?
Steps 1: Go to your ngrok folder location on your terminal
Step 2: Enter: ngrok config add-authtoken your_auth_id

Solution #2: Delete your account and recreate it or create an entirely new account on Ngrok. And don't forget to authenticate your token
 
Solution #3: If your issue is not solved or you keep getting the same error, reach out to Ngrok support team

**Comment by john9500** [comment]
@caseysoftware May be the code for next activity will not be there check that.

**Comment by josin11** [comment]
same how can i fix this

**Comment by ignacio-dev** [comment]
Why is this closed? It's still happening. Just randomly stopped working.

**Comment by caseysoftware** [comment]
This issue queue is unmonitored.

Please download the latest version from https://ngrok.com/download
and feel free to drop into https://ngrok.com/slack for support.

**Comment by shokeenamit** [comment]
I tried multiple attempts and seems I was able to make it working. below are the steps you may require to perform

You need to register with a different domain name first with below command, and try to get\post it using postman or insomania multiple times along with your local host.
- ngrok http --domain=new-domain-to-fix-error.com 8080

After this, re-run above command with original domain., e.g. 
- ngrok http --domain=original-domain-name.com 8080. 

It worked in my case. Hope it gonna work in your's too.

Thanks!

**Comment by edapess** [comment]
if anyone has this problem with `localhost` just redirect it not as `localhost` but `0000`

example

instead of 
`❯ ngrok http http://localhost:3333`

do this 

`❯ ngrok http http://0000:3333`
