### ISSUE TITLE
Disable ngrok ssl

### ISSUE THREAD

**Issue by Cbarness** [inconshreveable/ngrok#833]
New to ngrok. For fun Im wanting to host my own federated mastodon instance and thought I might setup at home on a raspberry pi 4 using ngrok with a reserved domain to tunnel but found I'm receiving an ssl error from mastodon. I assumed it was because mastodon was looking for a cert on my instance but receiving the one ngrok is handing out. For some reason even though I attempt to use the http address provided in my ngrok dashboard it always defaults to https when accessing localhost. Any ideas would be helpful.

**Comment by peterhoeg** [comment]
Maybe mastodon is using HSTS and thus forcing you to https since you've visited it over https once?

As for the SSL error, that would make be take on it as well.

If you want to host anything like mastodon, I'd recommend getting a USD5/month VPS somewhere with a public IP and use let's encrypt to get a proper cert.

**Comment by peterhoeg** [comment]
And by "host anything like mastodon" I meant "play around with hosting". If you actually want to host an instance with data you care about, you probably should get something better than a USD5/month VPS....

**Comment by Cbarness** [comment]
Yea really I'm not interested in the instance per se, it's more of can it actually be done. Can users on 2 instances on 2 different servers behind 2 different NATs send messages to each other. I'm just trying to test how it would resolve. If I'm running a full blown instance I wouldn't do it this way.

**Comment by peterhoeg** [comment]
To me this looks more like a mastodon SSL issue rather a ngrok limitation.

**Comment by roniemartinez** [comment]
Probably related to this issue.

Before, when I run `ngrok http 80` I get 2 URLs - one is HTTP and the other HTTPS.
But now, when I run the same command, I only get HTTPS.

Was there a recent change? Would there be an option to disable SSL?

**Comment by jide** [comment]
Same issue, I searched everywhere but couldn't find anything. :(

**Comment by jide** [comment]
Found this on the documentation website :

Only HTTPS tunnels by default - ngrok agent HTTP tunnels by default will only open a single HTTPS endpoint for your upstream service instead of both an HTTP and HTTPS endpoint. To enable both, you will need to add `--scheme http --scheme https` to your ngrok agent command or configuration file.

**Comment by roniemartinez** [comment]
@jide That worked! Thank you.

**Comment by caseysoftware** [comment]
These issues are unmonitored. Check out our Slack channel: http://ngrok.com/slack
