### ISSUE TITLE
Self Hosted ngrokd fails to allow client to connect

### ISSUE THREAD

**Issue by jacobfike** [inconshreveable/ngrok#84]
I compiled the release server with no certificates and am running it on my server with `-httpsAddr=""` to disable HTTPS.

When I try to connect with ngrok, I get this error on the server:

```
[01/28/14 15:58:20] [INFO] [pub:480e9ed0] New connection from 10.217.162.141:57544
[01/28/14 15:58:20] [WARN] [pub:480e9ed0] Failed to read valid http request: malformed HTTP request "\x16\x03\x01\x00X\x01\x00\x00T\x03\x01R\xe8D\x1c\x119:\x87\x19\xe1\xf5ձ\xbbl\xac5\xe2FuG\xb18\x8b[j{\x86\x1aG\xbf\xfa\x00\x00\x10\x00\x05\x00"
[01/28/14 15:58:20] [DEBG] [pub:480e9ed0] Closing
```

Any ideas?  Is this an encoding issue somewhere?

**Comment by gdtv** [comment]
I also have the problem. 
I use self-signed CA.
Finally, I solved the problem. 
The most important things is:
you must use the client that you compile ngrok with your signing CA. DONOT download the client from ngrok.com

**Comment by paoloantinori** [comment]
Hi guys, I'm trying to follow this guide without luck. I'm using https://gist.github.com/lyoshenka/002b7fbd801d0fd21f2f and the only different config in my step is that I'm providing directly ip address as NGROK_DOMAIN. 

When I open the https endpoint in the browser I see a correct request to accept a self signed certificate, but when I run the client,  it cannot connect, and I see this errors in server logs:

```
[03/25/15 08:37:36] [INFO] Listening for public http connections on [::]:8000
[03/25/15 08:37:36] [INFO] Listening for public https connections on [::]:8001
[03/25/15 08:37:36] [INFO] Listening for control and proxy connections on [::]:4443
[03/25/15 08:37:46] [INFO] [tun:2e91506e] New connection from xx.50.2.161:59970
[03/25/15 08:37:46] [DEBG] [tun:2e91506e] Waiting to read message
[03/25/15 08:37:46] [WARN] [tun:2e91506e] Failed to read message: remote error: bad certificate
[03/25/15 08:37:46] [DEBG] [tun:2e91506e] Closing
[03/25/15 08:37:48] [INFO] [tun:272901da] New conn
```

Any idea what I could be doing wrong?

I'm sure I'm using `ngrok` client I have built during the steps, to connect.

**Comment by prowayne** [comment]
### How can i remove the httpAddr?
```
Tunnel Status                 online
Version                       1.7/1.7
Forwarding                    http://wayne.ngrok.snowtigersoft.com:8080 -> 127.0
Web Interface                 127.0.0.1:4040
# Conn                        0
Avg Conn Time                 0.00ms
```

**Comment by kissthink** [comment]
how to add  auth service  as ngrok.com  by the  source ?  

> -authtoken="": Authentication token for identifying an ngrok.com account
> -httpauth="": username:password HTTP basic auth creds protecting the public

**Comment by facat** [comment]
how to add auth service as ngrok.com by the source ?

The same question to me. I cannot find official tutorial on this.

**Comment by kissthink** [comment]
yes , i had read some source code about it ,but noting found !
same question again  : how to  add auth service as ngrok.com ?

**Comment by fsamir** [comment]
+1 for some docs on auth on self hosted ngrokd.

**Comment by werty1st** [comment]
I finally got it by carefully reading the log output. after some hours i realized that the original client uses a ~/.ngrok2/ngrok.yml config file but the client i compiled used a file under ~/.ngrok

as this file was never created the client tried to connect to the wrong host.


my steps:
setup dns: python dnsproxy.py -H 127.0.1.1 -p 53 -s 8.8.8.8
to try things locally

create CA: like in post #issuecomment-34279559 without wildcard

replace files: rootCA.pem -> ngrokroot.crt, server.crt -> snakeoilca.crt, server.crt -> snakeoil.crt, server.key -> snakeoil.key

compile

config: ~/.ngrok  
server_addr: xxx.eu:4443
trust_host_root_certs: false

run: 
sudo ./ngrokd -tlsKey="server.key" -tlsCrt="server.crt" -domain="xxx.eu"
./ngrok -log=stdout 1337

thanks for this cool software

**Comment by elliott10** [comment]
If you encounter the following errors, that's because of `go1.15 X.509 CommonName deprecation`.
Setting environment `GODEBUG=x509ignoreCN=0` 
OR Compiling with <= go1.14

```
(ngrok/log.Error:120) control recovering from failure x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```

**Comment by tj0xin** [comment]
Hi all, 

I need help with this: 
I have a self hosted ngrok on digitalocean with letsencrypt certificate as well as wildcard domain. 
Created using the instructions mentioned in this link: [Self Hosted NGROK](https://medium.com/@shivanshvij/a-self-hosted-ngrok-45bcec06d0cf)

Now i can run ./ngrok 80 as well as with subdomain and proto (tcp) and its working Very well. now the problem was that while using tcp it used to get random port numbers on every restart so i made a ngrok.yml with the following options:

**ngrok.yml**

server_addr: domain.com:4443
tunnels:
   ssh:
    remote_port: 36523
    proto:
       tcp: 22 

**and started it with:**

./ngroks -config=ngrok.yml -log=ngrokn.log start ssh

**and it throws error:**

panic: Bad PEM data

goroutine 1 [running]:
ngrok/client.newClientModel(0x2068d00, 0x5495c8, 0x20166c0, 0x2009e0)
        /root/ngrok/src/ngrok/client/model.go:112 +0x698
ngrok/client.(*Controller).SetupModel(...)
        /root/ngrok/src/ngrok/client/controller.go:134
ngrok/client.(*Controller).Run(0x20166c0, 0x2068d00)
        /root/ngrok/src/ngrok/client/controller.go:150 +0xae0
ngrok/client.Main()
        /root/ngrok/src/ngrok/client/main.go:51 +0x1b8
main.main()
        /root/ngrok/src/ngrok/main/ngrok/ngrok.go:8 +0x14


**i have a .ngrok file in root which reads:**

server_addr: domain.com:4443
trust_host_root_certs: true

Tried with trust_host_root_certs: false but still doesn't work. 

If someone can shed some light on this please suggest what can be done to solve this.
